baseURL: "https://cv.prat.xyz/"
DefaultContentLanguage: 'fr'
languages:
  fr:
    languageName: "Fr"
    languageCode: "fr-fr"
    title: "SRE, Devops, Expert systèmes et réseaux"
    params:
      footerNotes: "Vous êtes arrivés ici et je vous remercie, si vous souhaitez savoir comment a été fait ce site, apporter un retour, ou une modification, [voici le code](https://github.com/saez0pub/cv)"
    weight: 1
  en:
    languageName: "En"
    languageCode: "en-us"
    title: "SRE, Devops, Systems and networks expert"
    params:
      footerNotes: "Thank you for reading, If you want to know how is made this site, give a feedback, or ask for modification, [here is the source code](https://github.com/saez0pub/cv)"
    weight: 2
theme: "cv"
disableKinds: ["taxonomy"]

params:
  image: "images/xkcd_friction_of_desk_chair_400x400.png"
  keywords: "Jean Prat Informatique P00LS LGO OAB Cheops Computer Cloud SRE Devops Devsecops Kubernetes Terraform"
  author: "Jean Prat"
  themecolor: "#325D72"
  icon: "images/apple_xkcd_friction_of_desk_chair_180x180.png"
  email: "job@prat.xyz"
  mobile: "+33677131316"
  navbar:
    stickytop: true
  social:
    - icon: "ti-linkedin"
      name: "LinkedIn"
      link: "https://www.linkedin.com/in/jean-prat-9a6b8715b/"
    - icon: "ti-github"
      name: "Github"
      link: "https://github.com/saez0pub"
    - icon: "ti-twitter-alt"
      hide_in_print: true
      name: "X"
      link: "https://x.com/JeanPrat"
  plugins:
    css:
      - link: "assets/css/themify-icons.css"
    js:
      - link: "assets/js/bootstrap.v5.3.8.bundle.js"
      - link: "assets/js/highcharts.js"
      - link: "assets/js/highcharts-more.js"